version: "3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik:v2.10"
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
    ports:
      - "8089:8089"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs/:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  rubytak:
    container_name: "rubytak"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8089
    labels:
      traefik.enable: true
      traefik.tcp.routers.rubytak.rule: HostSNI(`*`)
      traefik.tcp.routers.rubytak.tls: true

    networks:
      - proxy

networks:
  proxy:
    external: true
