# fly.toml file generated for ruby-tak on 2023-02-09T19:06:14+01:00

app = "ruby-tak"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = 8080

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
source="ruby_tak_config"
destination="/home/app/.config/ruby_tak"

[[statics]]
  guest_path = "/home/app/.config/ruby_tak/data_packages"
  url_prefix = "/data_packages"
