# fly.toml file generated for ruby-tak on 2023-02-09T19:06:14+01:00

app = "ruby-tak"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8089
  protocol = "tcp"

  [[services.ports]]
    port = 8089

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
source="ruby_tak_config"
destination="/root/.config/ruby_tak"
