# fly.toml file generated for ruby-tak on 2023-02-09T19:06:14+01:00

app = "ruby-tak"

[env]
  XDG_CONFIG_HOME = "/data/config"
  XDG_DATA_HOME = "/data/data"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8089
  protocol = "tcp"

  [[services.ports]]
    port = 8089

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
source="ruby_tak_config"
destination="/data"
