name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest
    name: Rake

    steps:
      - uses: actions/checkout@v4
        with:
          progress: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rake
        run: bundle exec rake
